wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.5
    start_time: 1674056982.897041
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.5
      5: 0.13.9
      8:
      - 2
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 5
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
